version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:5000:80
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
